using SplitGM.Core;
using System.Windows;
using System.Windows.Media;

namespace SplitGM.Gui;

/// <summary>
/// Read-only, resolution-independent waveform display for recovered GameMaker audio.
/// The control renders the real decoded minimum/maximum sample envelope generated by
/// the core waveform service; it does not synthesize or approximate audio data.
/// </summary>
public sealed class AudioWaveformControl : FrameworkElement
{
    private AudioWaveformInfo? _waveform;

    public AudioWaveformInfo? Waveform
    {
        get => _waveform;
        set
        {
            _waveform = value;
            ToolTip = value is null
                ? null
                : $"{value.DurationSeconds:0.###} s • {value.SampleRate:N0} Hz • {value.Channels} channel(s) • {value.Decoder}";
            InvalidateVisual();
        }
    }

    protected override void OnRender(DrawingContext drawingContext)
    {
        base.OnRender(drawingContext);

        double width = Math.Max(0, ActualWidth);
        double height = Math.Max(0, ActualHeight);
        drawingContext.DrawRectangle(new SolidColorBrush(Color.FromRgb(6, 9, 14)), null, new Rect(0, 0, width, height));

        if (width < 2 || height < 2)
            return;

        Pen centerPen = new(new SolidColorBrush(Color.FromRgb(39, 54, 74)), 1);
        centerPen.Freeze();
        drawingContext.DrawLine(centerPen, new Point(0, height / 2), new Point(width, height / 2));

        AudioWaveformInfo? waveform = _waveform;
        int count = waveform?.PointCount ?? 0;
        if (waveform is null || count == 0)
        {
            DrawCenteredText(drawingContext, "No decoded waveform is available.", width, height);
            return;
        }

        double center = height / 2;
        double amplitude = Math.Max(1, height * 0.43);
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            for (int index = 0; index < count; index++)
            {
                double x = count == 1 ? 0 : index * (width - 1) / (count - 1.0);
                double y = center - Math.Clamp(waveform.MaximumPeaks[index], -1, 1) * amplitude;
                if (index == 0)
                    context.BeginFigure(new Point(x, y), isFilled: true, isClosed: true);
                else
                    context.LineTo(new Point(x, y), isStroked: true, isSmoothJoin: true);
            }

            for (int index = count - 1; index >= 0; index--)
            {
                double x = count == 1 ? 0 : index * (width - 1) / (count - 1.0);
                double y = center - Math.Clamp(waveform.MinimumPeaks[index], -1, 1) * amplitude;
                context.LineTo(new Point(x, y), isStroked: true, isSmoothJoin: true);
            }
        }
        geometry.Freeze();

        Brush fill = new SolidColorBrush(Color.FromArgb(198, 32, 216, 255));
        Pen outline = new(new SolidColorBrush(Color.FromRgb(141, 241, 255)), 1);
        fill.Freeze();
        outline.Freeze();
        drawingContext.DrawGeometry(fill, outline, geometry);

        if (!waveform.IsComplete)
        {
            FormattedText warning = CreateText("Waveform preview truncated for safety", 11, new SolidColorBrush(Color.FromRgb(255, 196, 74)));
            drawingContext.DrawText(warning, new Point(8, 7));
        }
    }

    private static void DrawCenteredText(DrawingContext drawingContext, string text, double width, double height)
    {
        FormattedText formatted = CreateText(text, 13, new SolidColorBrush(Color.FromRgb(145, 158, 178)));
        drawingContext.DrawText(formatted, new Point(
            Math.Max(0, (width - formatted.Width) / 2),
            Math.Max(0, (height - formatted.Height) / 2)));
    }

    private static FormattedText CreateText(string text, double fontSize, Brush brush)
    {
        double pixelsPerDip = Application.Current?.MainWindow is Visual visual
            ? VisualTreeHelper.GetDpi(visual).PixelsPerDip
            : 1.0;

        return new FormattedText(
            text,
            System.Globalization.CultureInfo.CurrentUICulture,
            FlowDirection.LeftToRight,
            new Typeface("Segoe UI"),
            fontSize,
            brush,
            pixelsPerDip);
    }
}
